# Generated by Django 5.2.6 on 2025-09-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='cost_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per kg of feed', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='packet_size_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size of each packet in kg (e.g., 15kg, 25kg)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='cost_per_packet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per packet of feed', max_digits=8, null=True),
        ),
    ]
