# Generated by Django 5.2.6 on 2025-09-15 08:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0002_feed_cost_per_kg_feed_packet_size_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingadvice',
            name='average_fish_weight_kg',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Average fish weight in kg', max_digits=15),
        ),
        migrations.AlterField(
            model_name='feedingadvice',
            name='total_biomass_kg',
            field=models.DecimalField(decimal_places=10, help_text='Total fish biomass in kg', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fishsampling',
            name='average_weight_kg',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Average weight per fish in kg', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fishsampling',
            name='biomass_difference_kg',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Total biomass difference from previous sampling in kg', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fishsampling',
            name='fish_per_kg',
            field=models.DecimalField(decimal_places=10, help_text='Number of fish per kg', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fishsampling',
            name='growth_rate_kg_per_day',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Daily growth rate in kg', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='fishsampling',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=10, help_text='Total weight of sampled fish in kg', max_digits=15),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='avg_weight_kg',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='pieces_per_kg',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Pieces per kg', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=10, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='avg_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='mortality',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='initial_avg_weight_kg',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Initial average weight in kg', max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='pieces_per_kg',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Pieces per kg', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='total_weight_kg',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Total weight in kg', max_digits=15),
        ),
    ]
