# Generated by Django 5.2.6 on 2025-09-18 13:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0003_alter_feedingadvice_average_fish_weight_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingadvice',
            name='medical_considerations',
            field=models.TextField(blank=True, help_text='Medical considerations and adjustments made to feeding advice'),
        ),
        migrations.AddField(
            model_name='feedingadvice',
            name='medical_warnings',
            field=models.JSONField(default=list, help_text='Medical warnings and recommendations for this feeding advice'),
        ),
        migrations.CreateModel(
            name='MedicalDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(help_text='সম্ভাব্য রোগ (Possible Disease)', max_length=200)),
                ('confidence_percentage', models.DecimalField(decimal_places=2, help_text='Confidence percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommended_treatment', models.TextField(help_text='সুপারিশকৃত চিকিৎসা (Recommended Treatment)')),
                ('dosage_application', models.TextField(help_text='ডোজ ও প্রয়োগ (Dosage and Application)')),
                ('selected_organs', models.JSONField(default=list, help_text='Selected organs for diagnosis')),
                ('selected_symptoms', models.JSONField(default=list, help_text='Selected symptoms for diagnosis')),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('is_applied', models.BooleanField(default=False, help_text='Whether treatment has been applied')),
                ('applied_at', models.DateTimeField(blank=True, help_text='When treatment was applied', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_diagnostics', to='fish_farming.pond')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_diagnostics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Diagnostic',
                'verbose_name_plural': 'Medical Diagnostics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedingadvice',
            name='medical_diagnostics',
            field=models.ManyToManyField(blank=True, help_text='Related medical diagnostics that influenced this feeding advice', related_name='feeding_advice', to='fish_farming.medicaldiagnostic'),
        ),
    ]
