# Generated by Django 5.2.6 on 2025-09-19 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0004_feedingadvice_medical_considerations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='species', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicaldiagnostic',
            name='disease_name',
            field=models.CharField(help_text='Possible Disease', max_length=200),
        ),
        migrations.AlterField(
            model_name='medicaldiagnostic',
            name='dosage_application',
            field=models.TextField(help_text='Dosage and Application'),
        ),
        migrations.AlterField(
            model_name='medicaldiagnostic',
            name='recommended_treatment',
            field=models.TextField(help_text='Recommended Treatment'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='species',
            unique_together={('user', 'name')},
        ),
    ]
