# Generated by Django 5.2.6 on 2025-09-28 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0007_feedtype_level_feedtype_lft_feedtype_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedtype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='feedtype',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feed_types', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='feedtype',
            unique_together={('user', 'name', 'parent')},
        ),
    ]
