# Generated by Django 5.2.6 on 2025-09-28 10:57

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0008_add_user_to_feedtype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fish_farming.expensetype'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='fish_farming.incometype'),
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=10)),
                ('category', models.CharField(choices=[('feed', 'Feed'), ('medicine', 'Medicine'), ('equipment', 'Equipment'), ('labor', 'Labor'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('harvest', 'Harvest'), ('seedling', 'Seedling'), ('consulting', 'Consulting'), ('equipment_sales', 'Equipment Sales'), ('services', 'Services'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='fish_farming.accounttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['type', 'category', 'name'],
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='account_type',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 'expense'}, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fish_farming.accounttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='account_type',
            field=models.ForeignKey(default=1, limit_choices_to={'type': 'income'}, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='fish_farming.accounttype'),
            preserve_default=False,
        ),
    ]
