# Generated by Django 5.2.6 on 2025-09-28 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0009_add_account_type_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['type', 'name']},
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='category',
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('loan', 'Loan'), ('bank', 'Bank'), ('equity', 'Equity'), ('credit_card', 'Credit Card'), ('others', 'Others')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='account_type',
            field=models.ForeignKey(limit_choices_to={'type__in': ['expense', 'credit_card', 'loan']}, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='fish_farming.accounttype'),
        ),
        migrations.AlterField(
            model_name='income',
            name='account_type',
            field=models.ForeignKey(limit_choices_to={'type__in': ['income', 'bank', 'equity']}, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='fish_farming.accounttype'),
        ),
    ]
