# Generated by Django 5.2.6 on 2025-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0010_update_account_type_remove_category_expand_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocking',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost of stocking', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='initial_avg_weight_kg',
            field=models.DecimalField(decimal_places=10, default=0, help_text='Initial average weight per piece in kg (auto-calculated)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocking',
            name='pieces_per_kg',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Pieces per kg (auto-calculated)', max_digits=15, null=True),
        ),
    ]
