# Generated by Django 5.2.6 on 2025-09-28 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0011_add_cost_to_stocking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name or business name', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('country', models.CharField(default='Bangladesh', help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('customer_type', models.CharField(choices=[('individual', 'Individual'), ('retailer', 'Retailer'), ('wholesaler', 'Wholesaler'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('distributor', 'Distributor'), ('other', 'Other')], default='individual', help_text='Type of customer', max_length=50)),
                ('business_name', models.CharField(blank=True, help_text='Business name (if applicable)', max_length=200)),
                ('payment_terms', models.CharField(blank=True, help_text='Payment terms (e.g., Cash, Net 30)', max_length=100)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit', max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is customer active')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='Customer rating', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vendor/Supplier name', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State/Province', max_length=100)),
                ('country', models.CharField(default='Bangladesh', help_text='Country', max_length=100)),
                ('postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20)),
                ('business_type', models.CharField(choices=[('supplier', 'Supplier'), ('manufacturer', 'Manufacturer'), ('distributor', 'Distributor'), ('service_provider', 'Service Provider'), ('consultant', 'Consultant'), ('other', 'Other')], default='supplier', help_text='Type of business', max_length=50)),
                ('services_provided', models.TextField(blank=True, help_text='Services or products provided')),
                ('payment_terms', models.CharField(blank=True, help_text='Payment terms (e.g., Net 30)', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID or registration number', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is vendor active')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='Vendor rating', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
