# Generated by Django 5.2.6 on 2025-09-28 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0012_add_vendor_customer_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item or service name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('equipment', 'Equipment'), ('feed', 'Feed'), ('medicine', 'Medicine'), ('chemical', 'Chemical'), ('other', 'Other')], default='product', help_text='Type of item or service', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Category (e.g., Feed, Medicine, Equipment)', max_length=100)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (kg, liter, piece, etc.)', max_length=50)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit', max_digits=12, null=True)),
                ('currency', models.CharField(default='BDT', help_text='Currency code', max_length=10)),
                ('stock_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Current stock quantity', max_digits=15, null=True)),
                ('minimum_stock', models.DecimalField(blank=True, decimal_places=3, help_text='Minimum stock level for alerts', max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is item/service active')),
                ('is_available', models.BooleanField(default=True, help_text='Is currently available')),
                ('specifications', models.TextField(blank=True, help_text='Technical specifications')),
                ('usage_instructions', models.TextField(blank=True, help_text='Usage instructions')),
                ('storage_requirements', models.TextField(blank=True, help_text='Storage requirements')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date (if applicable)', null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Tax rate percentage', max_digits=5, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_services', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_services', to='fish_farming.vendor')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
