# Generated by Django 5.2.6 on 2025-09-28 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_farming', '0013_add_item_service_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemservice',
            name='feed_type',
            field=models.ForeignKey(blank=True, help_text='Feed type (only for feed items)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_services', to='fish_farming.feedtype'),
        ),
    ]
